services:
  - type: web
    name: mcp-form-automation
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
